### ISSUE TITLE
Issue: RSS importing currently broken

### ISSUE THREAD

**Issue by tomfinitely** [WordPress/rss-importer#3]
Debug returns the following error:

Fatal error: Uncaught Error: Call to undefined function set_magic_quotes_runtime()

A workaround is posted [here](https://stackoverflow.com/questions/46630924/call-to-undefined-function-set-magic-quotes-runtime), but I'm confident this isn't "the WordPress Way" of fixing the issue, however my knowledge in this area is limited.

**Comment by CtrlZmaster** [comment]
There is actually a pull request (#1) that fixes it and has been open for more than a year. I can't even put my frustration into words.

**Comment by tomfinitely** [comment]
Thank you for this. I find that raising awareness of long-forgetten PR's like this in the core contributor weekly Slack is actually very effective. I'll take it to them next week if no one responds in the core-importers channel.

**Comment by laozhoubuluo** [comment]
Seems publish version at https://wordpress.org/plugins/rss-importer/ still not update this bug fix yet.
